const HttpError = require('../utils/HttpError');
const effectiveStatus = require('./effectiveStatus');

const MISMATCH_THRESHOLD_CENTS = 50; // "more than 50 cents off" (BUILD PROMPT 4.3)

/**
 * All server-side state transitions for the fee ledger (BUILD PROMPT section
 * 4.3). Each function:
 *   - checks the actor's role (and partner ownership) and throws HttpError(403)
 *   - checks the instalment/batch/student's current state and throws
 *     HttpError(409) on a precondition violation (idempotent no-op per
 *     constraint #6)
 *   - mutates the passed-in Mongoose subdocuments/documents in place
 *   - returns a plain-object ledger event descriptor for the caller to
 *     persist as a FeeLedgerEvent
 *
 * Deliberately DB-agnostic: sequence numbers (RCPT-<seq>, sid, ...) are
 * generated by the caller (see services/sequence.js) and passed in, so these
 * functions can be unit-tested against plain in-memory objects.
 */

// Normalizes 'admin' to 'registrar' for permission checks — "admin can do
// everything registrar can" (BUILD PROMPT constraint #2), and admin is
// additionally allowed everywhere the table lists 'registrar', which is
// every gated action.
function assertRole(ctx, allowedRoles) {
  const role = ctx?.role;
  if (role === 'admin') return; // admin can do everything registrar (and thus partner-shared actions) can
  if (!role || !allowedRoles.includes(role)) {
    throw new HttpError(403, 'You do not have permission to perform this action.');
  }
}

function assertOwnsStudent(ctx, student) {
  if (ctx.role === 'partner' && String(student.partnerId) !== String(ctx.partnerId)) {
    throw new HttpError(403, 'You can only act on your own students.');
  }
}

function getInstalment(student, idx) {
  const inst = student.instalments?.[idx];
  if (!inst) throw new HttpError(404, 'Instalment not found');
  return inst;
}

/** partner (own student) or registrar/admin logs money they say they collected from the student. */
function logReceipt(student, idx, { amountCents, date }, ctx) {
  assertRole(ctx, ['partner', 'registrar']);
  assertOwnsStudent(ctx, student);

  const inst = getInstalment(student, idx);
  const status = effectiveStatus(inst, ctx.now);
  if (!['due', 'overdue'].includes(status)) {
    throw new HttpError(409, `Instalment is not open for a receipt (currently ${status}).`);
  }
  if (inst.channel !== 'agent') {
    throw new HttpError(409, 'Only agent-channel instalments accept a partner receipt.');
  }
  if (amountCents == null || amountCents < 0) {
    throw new HttpError(400, 'A valid amount is required.');
  }

  inst.status = 'agent';
  inst.reportedCents = amountCents;
  inst.collectedOn = date ? new Date(date) : new Date(ctx.now || Date.now());

  const diff = Math.abs(amountCents - inst.amountCents);
  const mismatch = diff > MISMATCH_THRESHOLD_CENTS;

  return {
    tag: mismatch ? 'MISMATCH' : 'AGENT WRITE',
    tone: mismatch ? 'bad' : 'warn',
    text: mismatch
      ? `${student.name} · ${inst.label}: partner reported $${(amountCents / 100).toFixed(2)}, invoiced $${(inst.amountCents / 100).toFixed(2)} (diff $${(diff / 100).toFixed(2)}).`
      : `${student.name} · ${inst.label}: partner logged a receipt of $${(amountCents / 100).toFixed(2)}.`,
  };
}

/** registrar/admin confirms cash actually landed in the college account. */
function confirmReceipt(student, idx, { rcptRef, mtcuRef }, ctx) {
  assertRole(ctx, ['registrar']);

  const inst = getInstalment(student, idx);
  if (inst.status === 'cleared') {
    throw new HttpError(409, 'This instalment is already confirmed.');
  }
  const readyAgent = inst.status === 'agent' && !inst.batchRef;
  const readyFunder = inst.status === 'funder';
  if (!readyAgent && !readyFunder) {
    throw new HttpError(409, `Instalment is not ready to confirm (status: ${inst.status}).`);
  }

  if (inst.reportedCents != null) inst.amountCents = inst.reportedCents;
  inst.status = 'cleared';
  inst.receiptRef = readyFunder ? `${mtcuRef} · ministry deposit` : `${rcptRef} · confirmed by registrar`;

  return {
    tag: 'CONFIRMED',
    tone: 'ok',
    text: `${student.name} · ${inst.label}: confirmed cleared ($${(inst.amountCents / 100).toFixed(2)}).`,
  };
}

/** registrar/admin records a student who paid the college directly. */
function recordDirect(student, idx, { amountCents, date, rcptRef }, ctx) {
  assertRole(ctx, ['registrar']);

  const inst = getInstalment(student, idx);
  const status = effectiveStatus(inst, ctx.now);
  if (!['due', 'overdue'].includes(status)) {
    throw new HttpError(409, `Instalment is not open for a direct payment (currently ${status}).`);
  }
  if (amountCents == null || amountCents < 0) {
    throw new HttpError(400, 'A valid amount is required.');
  }

  inst.channel = 'direct';
  inst.status = 'cleared';
  inst.amountCents = amountCents;
  inst.collectedOn = date ? new Date(date) : new Date(ctx.now || Date.now());
  inst.receiptRef = `${rcptRef} · paid direct`;

  return {
    tag: 'DIRECT',
    tone: 'ok',
    text: `${student.name} · ${inst.label}: paid direct to the college ($${(amountCents / 100).toFixed(2)}).`,
  };
}

/** registrar/admin submits a BJO instalment as a ministry claim. */
function submitClaim(student, idx, ctx) {
  assertRole(ctx, ['registrar']);
  if (student.fundingType !== 'bjo') {
    throw new HttpError(409, 'Only Better Jobs Ontario students have claims to submit.');
  }

  const inst = getInstalment(student, idx);
  const status = effectiveStatus(inst, ctx.now);
  if (!['due', 'overdue'].includes(status)) {
    throw new HttpError(409, `Claim is not open to submit (currently ${status}).`);
  }

  inst.status = 'funder';

  return {
    tag: 'BJO',
    tone: 'info',
    text: `${student.name} · ${inst.label}: submitted to the ministry ($${(inst.amountCents / 100).toFixed(2)}).`,
  };
}

/**
 * partner (own) or registrar/admin bundles several held instalments into one
 * remittance wire. `items` is [{ student, instalmentIndex }] — every
 * referenced instalment must be status 'agent' with no batchRef yet.
 */
function createBatch(items, { partnerId, batchRef }, ctx) {
  assertRole(ctx, ['partner', 'registrar']);
  if (ctx.role === 'partner' && String(partnerId) !== String(ctx.partnerId)) {
    throw new HttpError(403, 'You can only remit your own students.');
  }
  if (!items || items.length === 0) {
    throw new HttpError(400, 'A batch needs at least one instalment.');
  }

  let amountCents = 0;
  const batchItems = items.map(({ student, instalmentIndex }) => {
    assertOwnsStudent({ ...ctx, role: 'partner', partnerId }, student); // every student must belong to this partner
    const inst = getInstalment(student, instalmentIndex);
    if (inst.status !== 'agent' || inst.batchRef) {
      throw new HttpError(409, `${student.name} · ${inst.label} is not held-and-unbatched (status: ${inst.status}).`);
    }
    const itemAmount = inst.reportedCents != null ? inst.reportedCents : inst.amountCents;
    amountCents += itemAmount;
    inst.batchRef = batchRef;
    return { studentId: student._id, instalmentIndex, amountCents: itemAmount };
  });

  return {
    batchItems,
    amountCents,
    event: {
      tag: 'REMIT',
      tone: 'info',
      text: `Batch ${batchRef}: ${batchItems.length} instalment(s) sent for remittance ($${(amountCents / 100).toFixed(2)}).`,
    },
  };
}

/**
 * registrar/admin confirms an entire pending batch — clears every item in
 * one request and lets commission accrue on them (see services/commission.js).
 */
function confirmBatch(batch, students, { rcptRef }, ctx) {
  assertRole(ctx, ['registrar']);
  if (batch.status === 'reconciled') {
    throw new HttpError(409, 'This batch is already reconciled.');
  }
  if (batch.status !== 'pending') {
    throw new HttpError(409, `Batch is not pending (status: ${batch.status}).`);
  }

  batch.items.forEach((item) => {
    const student = students.find((s) => String(s._id) === String(item.studentId));
    if (!student) throw new HttpError(404, `Student ${item.studentId} not found for batch ${batch.ref}`);
    const inst = getInstalment(student, item.instalmentIndex);
    if (inst.reportedCents != null) inst.amountCents = inst.reportedCents;
    inst.status = 'cleared';
    inst.receiptRef = `${rcptRef} · batch ${batch.ref} · wire ${batch.wireRef}`;
  });

  batch.status = 'reconciled';
  batch.confirmedOn = new Date(ctx.now || Date.now());

  return {
    tag: 'RECONCILED',
    tone: 'ok',
    text: `Batch ${batch.ref} reconciled — ${batch.items.length} instalment(s) cleared ($${(batch.amountCents / 100).toFixed(2)}).`,
  };
}

/** registrar/admin approves a withdrawal refund, cancelling remaining unpaid instalments. */
function approveRefund(student, refundResult, ctx) {
  assertRole(ctx, ['registrar']);
  if (student.withdrawal) {
    throw new HttpError(409, 'This student has already withdrawn.');
  }

  student.instalments.forEach((inst) => {
    const status = effectiveStatus(inst, ctx.now);
    if (status === 'due' || status === 'overdue') inst.cancelled = true;
  });

  student.withdrawal = {
    date: refundResult.noticeDate,
    reason: refundResult.reason,
    refundCents: refundResult.refundCents,
    clawbackCents: refundResult.clawbackCents,
  };

  return {
    tag: 'REFUND',
    tone: refundResult.refundCents > 0 ? 'warn' : 'info',
    text: `${student.name}: withdrawal approved (${refundResult.reason}) — refund $${(refundResult.refundCents / 100).toFixed(2)}, clawback $${(refundResult.clawbackCents / 100).toFixed(2)}.`,
  };
}

/** registrar/admin creates a new fee-ledger student from a program + funding type + cohort start. */
function createStudent({ programId, program, fundingType, partnerId }, ctx) {
  assertRole(ctx, ['registrar']);
  if (!program || !program.active) {
    throw new HttpError(400, 'A valid, active program is required.');
  }
  if (fundingType === 'intl' && !partnerId) {
    throw new HttpError(400, 'An intl (agent-recruited) student requires a recruiting partner.');
  }
  if (fundingType !== 'intl' && partnerId) {
    throw new HttpError(400, 'Only intl students can have a recruiting partner.');
  }

  return {
    tag: 'NEW',
    tone: 'ok',
    text: `New ${fundingType} student added to ${program.name}.`,
  };
}

module.exports = {
  assertRole,
  assertOwnsStudent,
  logReceipt,
  confirmReceipt,
  recordDirect,
  submitClaim,
  createBatch,
  confirmBatch,
  approveRefund,
  createStudent,
  MISMATCH_THRESHOLD_CENTS,
};
