import { useEffect, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card.jsx';
import { Button } from '@/components/ui/button.jsx';
import { Badge } from '@/components/ui/badge.jsx';
import { formatDate } from '@/lib/utils';
import * as api from '@/lib/api';

/**
 * The counsellor dashboard's "Today" widget from the spec — due/overdue
 * follow-ups at a glance, with a one-click "mark done".
 */
export default function CounsellorTodayPanel() {
  const [tasks, setTasks] = useState([]);
  const [loading, setLoading] = useState(true);

  const load = () => {
    setLoading(true);
    api
      .fetchTasks({ today: true })
      .then((res) => setTasks(res.data))
      .finally(() => setLoading(false));
  };

  useEffect(load, []);

  const markDone = async (id) => {
    await api.updateTask(id, { status: 'Done' });
    setTasks((prev) => prev.filter((t) => t._id !== id));
  };

  const overdue = tasks.filter((t) => new Date(t.dueDate) < new Date(new Date().setHours(0, 0, 0, 0)));

  return (
    <Card className="mb-6">
      <CardHeader>
        <CardTitle className="text-base flex items-center gap-2">
          Today
          <Badge variant="secondary">{tasks.length} due</Badge>
          {overdue.length > 0 && <Badge variant="warning">{overdue.length} overdue</Badge>}
        </CardTitle>
      </CardHeader>
      <CardContent>
        {loading ? (
          <p className="text-sm text-muted-foreground">Loading tasks...</p>
        ) : tasks.length === 0 ? (
          <p className="text-sm text-muted-foreground">Nothing due today. 🎉</p>
        ) : (
          <ul className="space-y-2">
            {tasks.map((task) => (
              <li key={task._id} className="flex items-center justify-between gap-3 rounded-md border p-3 text-sm">
                <div>
                  <p className="font-medium text-gray-900">{task.description}</p>
                  <p className="text-xs text-muted-foreground">
                    {task.student?.name} &middot; due {formatDate(task.dueDate)}
                    {task.autoGenerated && ' · auto-generated'}
                  </p>
                </div>
                <Button size="sm" variant="outline" onClick={() => markDone(task._id)}>
                  Mark Done
                </Button>
              </li>
            ))}
          </ul>
        )}
      </CardContent>
    </Card>
  );
}
