const mongoose = require('mongoose');

/**
 * Follow-up / to-do items for counsellors — powers the "Today" widget on
 * the counsellor dashboard (follow-ups, calls, document chases) and the
 * automation flows that auto-create a task (e.g. "Missing document →
 * counsellor task" from the spec).
 */
const TaskSchema = new mongoose.Schema(
  {
    student: { type: mongoose.Schema.Types.ObjectId, ref: 'Student', required: true },
    assignedTo: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },

    type: {
      type: String,
      enum: ['Follow-up', 'Call', 'Document Request', 'Application Task', 'Other'],
      default: 'Follow-up',
    },
    description: { type: String, trim: true, required: true, maxlength: 500 },
    dueDate: { type: Date, required: true },
    status: {
      type: String,
      enum: ['Pending', 'Done', 'Cancelled'],
      default: 'Pending',
    },
    completedAt: Date,

    // Marks tasks created by automation (vs. manually by a counsellor) so the
    // UI can label them distinctly and so automation doesn't create duplicates.
    autoGenerated: { type: Boolean, default: false },
  },
  { timestamps: true }
);

TaskSchema.index({ assignedTo: 1, status: 1, dueDate: 1 });
TaskSchema.index({ student: 1 });

module.exports = mongoose.model('Task', TaskSchema);
