const Task = require('../models/Task');
const User = require('../models/User');
const { scoreLead } = require('./leadScoring');
const { autoAssignCounsellor } = require('./autoAssignCounsellor');
const { sendWhatsApp } = require('./messaging');
const { sendLeadAutoReply, sendTeamNotification, sendCounsellorNewLeadAlert } = require('./sendEmail');

/**
 * Runs the automation chain from the spec for every new public submission:
 *   Lead Created → Lead Score → Counsellor Assigned → WhatsApp ack →
 *   Email ack → Counsellor + admin notification → Follow-up task
 *
 * Each step is independently fire-and-forget-safe: a failure in one (e.g.
 * email misconfigured) never blocks the others or the API response.
 */
const onboardNewLead = async (student) => {
  const results = { leadScore: null, assignedCounsellor: null, followUpTask: null };

  try {
    student.leadScore = scoreLead(student);
    results.leadScore = student.leadScore;

    const counsellorId = await autoAssignCounsellor();
    if (counsellorId) {
      student.assignedCounsellor = counsellorId;
      results.assignedCounsellor = counsellorId;
    }

    await student.save();
  } catch (err) {
    console.error('Lead scoring/assignment failed:', err.message);
  }

  // Fire-and-forget notifications — don't let a slow/misconfigured channel
  // block the caller.
  sendLeadAutoReply(student).catch((err) => console.error('Auto-reply email failed:', err.message));
  sendTeamNotification(student).catch((err) => console.error('Team notification email failed:', err.message)); // admin/team inbox
  sendWhatsApp({
    student,
    message: `Hi ${student.name.split(' ')[0]}, thanks for reaching out to CanadaDigitoba! A counsellor will contact you within 1-2 business days.`,
  }).catch((err) => console.error('WhatsApp acknowledgement failed:', err.message));

  // Individual alert to the counsellor this lead was just assigned to, on
  // top of the shared team inbox above.
  if (student.assignedCounsellor) {
    User.findById(student.assignedCounsellor)
      .select('name email')
      .then((counsellor) => sendCounsellorNewLeadAlert(student, counsellor))
      .catch((err) => console.error('Counsellor new-lead alert failed:', err.message));
  }

  if (student.assignedCounsellor) {
    try {
      const dueDate = new Date();
      dueDate.setDate(dueDate.getDate() + 1); // follow up within 1 business day
      results.followUpTask = await Task.create({
        student: student._id,
        assignedTo: student.assignedCounsellor,
        type: 'Follow-up',
        description: `Initial follow-up call for new lead: ${student.name}`,
        dueDate,
        autoGenerated: true,
      });
    } catch (err) {
      console.error('Follow-up task creation failed:', err.message);
    }
  }

  return results;
};

module.exports = { onboardNewLead };
